Add overlay for r8s (Samsung Galaxy S20 FE 4G Exynos)
phhusson/vendor_hardware_overlay pull request #375
Opened 2021-07-02 03:37 UTC by adil192

This doesn't fix the display corner radius though :(

2021-07-02 03:48 UTC, adil192 commented
tests failed, will fix in the morning

2021-07-02 13:59 UTC, adil192 commented
Display corner radius is still too round, any pointers?

2021-07-04 18:44 UTC, phhusson requested changes
Those settings looks really fishy to me.

If I had to guess, you extracted them from /system/framework/framework-res.apk, but you have overlays in /vendor/overlay, that have the actual correct values.

All those XML (except power profile) are totally off-topic

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/values/bools.xml
> +    <bool name="config_pinnerCameraApp">false</bool>
Sounds stupid on a 6GB RAM device

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/values/bools.xml
> +    <bool name="config_enableBurnInProtection">false</bool>
Sounds really weird on an OLED device

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/values/bools.xml
> +    <bool name="config_supportAudioSourceUnprocessed">false</bool>
This is a requirement for non-low-end device since Nougat, pretty sure that's wrong

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/values/bools.xml
> +    <bool name="config_setColorTransformAccelerated">false</bool>
On a 500€+ device? That sounds highly unlikely.

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/values/bools.xml
> +    <bool name="config_sustainedPerformanceModeSupported">false</bool>
Pretty sure it does.

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/values/strings.xml
> +    <string name="config_cameraLaunchGestureSensorStringType" />
Let's just not declare it then...?

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/xml/apns.xml
> +<?xml version="1.0" encoding="utf-8"?>
?

2021-07-04 18:44 UTC, phhusson commented on Samsung/r8s/res/xml/audio_assets.xml
> +<audio_assets version="1.0">
What does this have to do with hardware? If you want  TouchWiz, just use stock ROM

2021-07-05 19:58 UTC, adil192 commented
> Those settings looks really fishy to me.
> 
> If I had to guess, you extracted them from /system/framework/framework-res.apk, but you have overlays in /vendor/overlay, that have the actual correct values.
> 
> All those XML (except power profile) are totally off-topic

sorry, I forgot to close this pull request. I've moved onto the main branch rather than the pie branch. I'll add your changes there if still needed

2021-07-05 19:58 UTC, closed without merging

2021-08-12 19:50 UTC, KHOENIX commented
Leave a comment