Added Galaxy A31 Device & Ui Overlays
phhusson/vendor_hardware_overlay pull request #612
Opened 2022-07-31 17:57 UTC by DevZillion

2022-08-24 20:41 UTC, phhusson requested changes
Is it tested? Your power_profile is utterly broken.

2022-08-24 20:41 UTC, phhusson commented on Samsung/A31/res/xml/power_profile.xml
> +    <item name="battery.capacity">1000</item>
Doubt.

2022-08-24 20:41 UTC, phhusson commented on Samsung/A31/res/xml/power_profile.xml
> +    <item name="screen.on">0.1</item>
A screen that consumes 0.1mA at max  brightness? awesome ! Sounds physically impossible but well...

2022-08-24 20:41 UTC, phhusson commented on Samsung/A31/res/xml/power_profile.xml
> +    <array name="cpu.active">
Sounds unlikely.

2022-08-24 20:49 UTC, DevZillion commented
Sorry about the power_profile.xml.
An XDA gyide recommended to extract it from framework-res.apk, thx anyways for the requested changes and I'll fix them as fast as I can.

2022-08-24 20:50 UTC, DevZillion commented
And yeah I tested it, what I don't know if what the power_profile overlay does so that's the most untested.

2022-08-24 20:50 UTC, DevZillion commented
And yeah I tested it, what I don't know if what the power_profile overlay does so that's the most untested.

2022-08-25 07:22 UTC, DevZillion commented
Ok I've took some values from power_profile_test.xml inside framework-res.apk
Now they see to have more sense

2022-09-07 16:39 UTC, merged